apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: tburmaster/python-helloworld:$(date +%Y%m%d%H%M%S)
        ports:
        - containerPort: 5000